name: Run API Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: christiandezha
          POSTGRES_DB: ecomm_x_test
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache/@v4
        with:
          path: ~/.npm
          key: ${{runner.os}}-node-${{hashFiles('package-lock.json')}}
          restore-keys: |
            ${{runner.os}}

      - name: Install dependencies
        run: npm ci

      - name: Create .env.test
        run: |
          echo "PORT=3000" >> .env.test
          echo "PG_DB_TEST=ecomm_x_test" >> .env.test
          echo "PGUSER=christiandezha" >> .env.test
          echo "PGPASSWORD=${{secrets.POSTGRES_PASSWORD}}" >> .env.test
          echo "SALT_ROUNDS=${{ secrets.SALT_ROUNDS }}" >> .env.test
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.test
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env.test
          echo "YUKI_PASSWORD=${{ secrets.YUKI_PASSWORD }}" >> .env.test
          echo "PIERRE_PASSWORD=${{ secrets.PIERRE_PASSWORD }}" >> .env.test

      - name: Set .env file
        run: cp .env.test .env

      - name: Build
        run: npm run build

      - name: Run migrations
        run: npx knex migrate:latest --env test

      - name: Run seeds
        run: npx knex seed:run --env test

      - name: Run tests
        run: npm run test:ci
